language: java

jdk:
  - oraclejdk8
  - openjdk6

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"

script: ./travis-build.sh

cache:
  directories:
  - $HOME/.gradle

sudo: false

#notifications:
#  email:
##    - dev@tapestry.apache.org
